### ISSUE TITLE
Faster plot swapping

### ISSUE THREAD

**Issue by jomo** [RedstonerServer/Parcels#2]
I'm not sure if the Spigot/Bukkit API allows this, but it might be worth looking into copying/moving complete chunks. Plots obviously don't align with the chunk grid, but any plot >= 32x32 blocks has _at least_ one full chunk in it.

I feel like the game is loading complete chunks _much_ faster than 65536 single blocks and maybe we can use this, too!
Would it be possible to generate a new chunk over an existing one? Maybe the chunk can be regenerated using a temporary ChunkGenerator with the swapped chunk as a source for the ChunkData?

**Comment by Dico200** [comment]
Judging from the Spigot docs, there does not appear to be a very good way of making this happen properly. The only thing I can think of is to use reflection to change the ChunkGenerator instance of a world temporarily, which I will attempt, but it's very hacky and can definitely not be done asynchronously. After all, we don't want other chunks to be generated while this happens.

**Comment by Dico200** [comment]
Parcels now does its block operations in a manner where it executes the task and pauses when it hits an amount of time, so it doesn't lag the server if configured correctly. It's nice to watch too. 
Performance is about 3.5 seconds for a plot clear of redstoner size on my core i5 laptop while also running minecraft, the mysql server, a browser, and what not. 
Plot swap is a different story and I don't have an accurate number. It might be a bit long but it doesn't lag at least.
